### PR TITLE
Add General Feedback issue template

### PR DESCRIPTION
**Pull request by jeff2d2**
This PR addresses [this issue](https://github.com/department-of-veterans-affairs/vets-contrib/issues/1723) and creates a new `General Feedback` issue template.

### CODE REVIEW

**Comment by Eallan919** [comment]
@jeff2d2 I like it! Maybe adding a blurb to thank them and/or make them feel part of our mission.  "We are in this together" ... maybe that is too mushy?!?!?!

"We are continually striving to improve our process and APIs. Your input and feedback ensures we are serving both Veterans and you, our developers.  Thank you!"

Other than that, LGTM. Curious to know if UX has more input!

**Comment by tristarowan** [comment]
Wow--this happened super fast--way to go!!!  And this wording is fantastic:

"We are continually striving to improve our process and APIs. Your input and feedback ensures we are serving both Veterans and you, our developers. Thank you!" 

But a quick question: will all folks giving feedback be developers?  That's my only nitpick. If that were the case, I might recommend modifying it slightly to say  "...serving both Veterans and people like you. Thank you!"

**Comment by jeff2d2** [comment]
> Could we add a way for the user to give general feedback, too? The questions are quite specific and may not cover all kinds of feedback, such as usability comments, etc. Maybe just an extra line that says "Do you have any additional feedback?"

Those were intended to just be prompts to get them thinking. Do you think there's a better way to call out that that's what those are for?

I made the edits suggested. Let me know what you think!

**Comment by tristarowan** [comment]
@jeff2d2 thanks for including the general feedback prompt--looks great!

**Comment by jeff2d2** [comment]
> Looks good! My only thought is that people may not know what PII and PHI actually are. Even though we define the acronyms, it might be good to toss in some specific data that we don't want included here!

Good call @kalilsn. @tristarowan any suggestions here?

**Comment by juliaelman** [comment]
@kalilsn agreed. We should be specific on what information they should not include.

@jeff2d2 can you tell me why email address is included in the template?

**Comment by dvogel** [comment]
> @kalilsn agreed. We should be specific on what information they should not include.
> 
> @jeff2d2 can you tell me why email address is included in the template?

Ditto to both of these points. They could interact poorly because asking them to exclude PII and then asking for their email address can be contradictory. E.g. my email address is drewpvogel@gmail.com. Lots of people porn in 1982 will have an email address like drew82@geocities.com.

Regardless of whether an email address is considered PII, I think if we get to point in our effort to support them where it's appropriate to transition to email, it would be best for us to reply to the issue with a request that they email a specific shared email address to continue support.

**Comment by jeff2d2** [comment]
Agreed @dvogel. I think that was the original intent: so we can contact them directly if need be, but I like your route better.

I'll submit another PR to remove email from the rest of them too.

On Apr 5, 2019, at 2:36 PM, Drew Vogel <notifications@github.com> wrote:

@kalilsn agreed. We should be specific on what information they should not include.

@jeff2d2 can you tell me why email address is included in the template?

Ditto to both of these points. They could interact poorly because asking them to exclude PII and then asking for their email address can be contradictory. E.g. my email address is drewpvogel@gmail.com. Lots of people porn in 1982 will have an email address like drew82@geocities.com.

Regardless of whether an email address is considered PII, I think if we get to point in our effort to support them where it's appropriate to transition to email, it would be best for us to reply to the issue with a request that they email a specific shared email address to continue support.

**Comment by jeff2d2** [comment]
@kalilsn @dvogel @juliaelman new commits ready for review

**Comment by jeff2d2** [comment]
[A list of all example PHI is extensive](http://www.irb.emory.edu/documents/phi_identifiers.pdf)(and even this list has an `etc.` at the bottom), so I only included some of the basics here.

**Pull request merged**
