### PR TITLE
Updates file structure for sample apps, fix readme

### PR DESCRIPTION
**Pull request by jeff2d2**
This PR moves the sample node app into `/samples` and modifies the README for that move + a typo.

### CODE REVIEW

**Comment by dvogel** [comment]
I'm hoping we can take "vetconfirmation" out of the directory name. I've recently written up an epic to unify the features of the sample apps: https://github.com/department-of-veterans-affairs/vets-contrib/issues/1857. I hope we can have each sample app be specific to a technology stack but expose the same features as much as possible. Having to use a different tech stack to test the veteran confirmation API versus the health API is a frustrating experience. It's especially frustrating when trying to determine why something isn't working because you can't change just one thing.

Separately issue: we link to this node app from the developer portal. We should update that link in the developer portal. Since the developer portal aggressively caches itself using service workers, we should also add a symlink from the old location in this repo to the new location, to avoid broken links for users seeing the cached portal content.

**Comment by nfasulo** [comment]
@dvogel good catch on needing to update the developer portal. I actually found a small typo in the OAuth page this morning, so I can change the path to the node sample app when I fix it.

Unless you're suggesting we hold off on moving the node sample app until we have a larger discussion about where these apps should go . . .

**Comment by dvogel** [comment]
> Unless you're suggesting we hold off on moving the node sample app until we have a larger discussion about where these apps should go . . .

I'm not suggesting we delay. I'm just suggesting we update this PR to change the directory name like so (forgive my ad hoc diff format):

```
- oauth/node/README.md → samples/oauth_node_vetconfirmation/README.md 
+ oauth/node/README.md → samples/oauth_node/README.md 
```

For context, I'm also hoping we can merge the two rails apps in the future. It feels superfluous to demonstrate different APIs in different sample apps with the same tech stack.

**Comment by jeff2d2** [comment]
@dvogel Do you think we should we rename the other ones as well while we're at it? Have to do something special though for the rails apps as there are 2 distinct ones:
```
+ samples/oauth_rails_vetverification → samples/oauth_rails/vetverification
+ samples/oauth_rails_vethealth/README.md → samples/oauth_rails/vethealth/README.md
+ samples/oauth-react-vetverification/README.md → samples/oauth_react/README.md
```

**Comment by dvogel** [comment]
> @dvogel Do you think we should we rename the other ones as well while we're at it? Have to do something special though for the rails apps as there are 2 distinct ones:
> 
> ```
> + samples/oauth_rails_vetverification → samples/oauth_rails/vetverification
> + samples/oauth_rails_vethealth → samples/oauth_rails/vethealth
> + samples/oauth-react-vetverification → samples/oauth_react
> ```

I'd be down with that, sure.

**Comment by jeff2d2** [comment]
Before this is RTM @erluti is going to fix what will become some broken links in his sample app docs

**Comment by jeff2d2** [comment]
OK, this should now be ready for review again @nfasulo @dvogel.

**Pull request merged**
