### PR TITLE
Add version 0.4.0 Design Doc

### PR DESCRIPTION
**Pull request by ayaleloehr**
Closes https://github.com/department-of-veterans-affairs/vets-contrib/issues/133

Changes made are listed in the changelog at the end of the doc (I know diffs are hard to see in PDFs in GitHub).

### CODE REVIEW

**Comment by ayaleloehr** [comment]
not urgent, but pinging here to get this in and avoid any future merge conflicts.

**Comment by patrickvinograd** [comment]
I'm going to make these updates to the source document that I've been managing, and re-upload it along with the description of the processing flow provided by Michael Taylor.

**Comment by patrickvinograd** [comment]
@ayaleloehr Please give a quick review of the additional document I added, I wanted to make sure and capture that info but it doesn't belong in the API spec precisely.

**Comment by patrickvinograd** [comment]
Feel free to make any adjustments and merge.

**Pull request merged**
